version: '3'
services:
  #  server:
  #    image: node:14.10
  #    restart: always
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - /media:/media
  #      - ./:/app
  #      - uploads:/app/uploads
  #      - node_modules:/app/node_modules
  #    working_dir: /app
  #    depends_on:
  #      - mongodb
  #    command: sh -c "yarn install --non-interactive --ignore-scripts; node index.js"
  mongodb:
    restart: always
    image: mongo:3.6
    ports:
      - 5000:27017
    volumes:
      - slideshow_mongo:/data/db

volumes:
  slideshow_mongo:
    #  node_modules:
    #  uploads:
